#!/bin/sh -ex

if [ $1 = "all" ];
then
    # not implemented - test all testbench targets
    >&2 echo "Error: build.sh failed, 'all' target not yet implemented'";
    exit;
else
    # just test against the $1 target
    module=$1;
fi


# cleanup
rm -rf ./obj_dir
rm -f ./src/${module}.vcd

mkdir -p ./obj_dir

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace ./src/${module}.sv --exe ./src/${module}_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C ./obj_dir/ -f V${module}.mk V${module}

# run executable simulation file
./obj_dir/V${module}